# Generated by Django 6.0.2 on 2026-02-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='shortlisted',
            field=models.BooleanField(default=False),
        ),
    ]
