# Generated by Django 6.0.2 on 2026-02-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_candidate_status_alter_candidate_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='shortlisted',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
