# Generated by Django 6.0.2 on 2026-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_candidate_job_role_alter_candidate_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job_role',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='ai_feedback',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='JobRole',
        ),
    ]
