# Generated by Django 6.0.2 on 2026-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_jobrole_candidate_job_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='skills',
            field=models.TextField(default='Not specified', help_text='Comma separated skills (e.g. Python, Django, AI)'),
            preserve_default=False,
        ),
    ]
