# Generated by Django 6.0.2 on 2026-02-25 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_jobrole_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='interview_stage',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Round 1', 'Round 1'), ('Round 2', 'Round 2'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='job_role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobrole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='skills',
            field=models.TextField(help_text='Format: Python:3, Django:2, AI:4, SQL:1'),
        ),
    ]
