# Generated by Django 6.0.2 on 2026-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_candidate_interview_stage_alter_candidate_job_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='interview_stage',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Round 1', 'Round 1'), ('Round 2', 'Round 2'), ('HR', 'HR'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='skills',
            field=models.TextField(),
        ),
    ]
