# Generated by Django 6.0.2 on 2026-02-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_alter_candidate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='certification_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='grade',
            field=models.CharField(default='C', max_length=5),
        ),
        migrations.AddField(
            model_name='candidate',
            name='level',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Professional', 'Professional'), ('Expert', 'Expert')], default='Fresher', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
