# Generated by Django 6.0.2 on 2026-02-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_candidate_certification_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
