# Generated by Django 6.0.2 on 2026-02-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_alter_candidate_grade_alter_candidate_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='certification_score',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='education_score',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='experience_score',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='level',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='reject_reason',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skill_score',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='interview_stage',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Round 1', 'Round 1'), ('Round 2', 'Round 2'), ('Rejected', 'Rejected')], default='Not Started', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='skills',
            field=models.TextField(help_text='Example: Python:5, Django:4, AI:3'),
        ),
    ]
