# Generated by Django 6.0.2 on 2026-02-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_candidate_created_at_alter_candidate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='created_at',
        ),
        migrations.AddField(
            model_name='candidate',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='recruiter_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
